# Generated by Django 5.2.3 on 2025-06-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('hash', models.CharField(max_length=100)),
                ('color_histogram', models.JSONField()),
                ('object_list', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
